# Use the official .NET SDK image as the base image
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

WORKDIR /src
EXPOSE 80

# Copy the project file and restore dependencies
COPY ["WebAPIDemo.csproj", "./"]
RUN dotnet restore

# Copy the rest of the source code and build the application
COPY . .
RUN dotnet publish "WebAPIDemo.csproj" -c Release -o /app

# Use a smaller runtime image for the final image
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "MvcApplication1.dll"]
