# Use the official .NET SDK image as the base image
FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build

WORKDIR /src
EXPOSE 80

# Copy the project file and restore dependencies
COPY ["WebAPI.csproj", "WebAPI/"]
RUN dotnet restore "WebAPI.csproj"

# Copy the rest of the source code and build the application
COPY . .
RUN dotnet publish "WebAPI.csproj" -c Release -o /app

# Use a smaller runtime image for the final image
FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS runtime

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "WebAPI.dll"]

