name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Setup .NET
        uses: actions/checkout@v3
        
      - name: Setup DotNet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Build .NET Backend
        run: |
          cd WEBAPIUPDATED\WebAPI
          ls  # List contents to verify you are in the right directory

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
