name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Setup .NET
        uses: actions/checkout@v3
        
      - name: Setup DotNet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Build .NET Backend
        run: |
          cd WEBAPIUPDATED\WebAPI
          dotnet publish -c Release -o published
          ls  # List contents to verify you are in the right directory
          echo "::set-output name=backend_path::WEBAPIUPDATED\WebAPI\published"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          cd AngularCRUD
          npm install

      - name: Build and Test Angular Frontend
        run: |
          cd AngularCRUD
          npm run build 

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: WEBAPIUPDATED\WebAPI\published

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: AngularCRUD/dist
          
  deploy:
    needs: build
    runs-on: windows-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-artifact
          path: WEBAPIUPDATED\WebAPI\published

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact
          path: AngularCRUD/dist

      - name: Copy file to IIS
        run: |
          #copy .net 
          #cp -r WEBAPIUPDATED\WebAPI\published\* "D:\AngularWEBapi"
          Copy-Item -Path "$env:GITHUB_WORKSPACE\WEBAPIUPDATED\WebAPI\published\*" -Destination "D:\AngularWEBapi" -Recurse -Force
           # Copy Angular Frontend
          Copy-Item -Path "$env:GITHUB_WORKSPACE\AngularCRUD\dist\*" -Destination "D:\AngularWebAPI" -Recurse -Force
          
      # - name: Copy Agular Frontend to IIS
      #   run: |
      #     cp -r AngularCRUD/dist/* "D:\AngularWEBapi"

    
