name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Setup .NET
        uses: actions/checkout@v3
        
      - name: Setup DotNet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Build .NET Backend
        run: |
          cd WEBAPIUPDATED\WebAPI
          dotnet publish -c Release -o published
          ls  # List contents to verify you are in the right directory
          echo "::set-output name=backend_path::WEBAPIUPDATED\WebAPI\published"
          
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: WEBAPIUPDATED\WebAPI\published


  deploy:
    needs: build
    runs-on: self-hosted
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-artifact
          path: WEBAPIUPDATED\WebAPI\published

      - name: Debugging
        run: |
           Write-Host "Listing contents of backend artifact:"
           Get-ChildItem -Path "$env:GITHUB_WORKSPACE\WEBAPIUPDATED\WebAPI\published" -Recurse


      - name: Copy backend to IIS
        run: |
          Write-Host "Copying backend to D:\AngularWEBapi"
          Copy-Item -Path "$env:GITHUB_WORKSPACE\WEBAPIUPDATED\WebAPI\published\*" -Destination "D:\AngularWEBapi" -Recurse -Force


    
